stages:
  - local-test

static-analysis:
  stage: local-test
  tags:
    - docker
  script:
    - 'static-analysis.sh'
  allow_failure: true
  except:
    - master

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'
  except:
    - master

unit-test-python27:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh'
  allow_failure: true
  except:
    - master

unit-test-python36:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh python36'
  allow_failure: true
  except:
    - master

coverage-python36:
  stage: local-test
  tags:
    - docker
  script:
    - 'coverage-virtualenv.sh python36'
  coverage: '/TOTAL.*\s+(\d+%)$/'
  allow_failure: true
  except:
    - master
